name: codigoqr
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  mobile_scanner: ^4.0.1
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.4
  path_provider: ^2.0.13
  permission_handler: ^11.0.1
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  encrypt_decrypt_plus: ^1.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.4
  flutter_slidable: ^3.1.0
  flutter_riverpod: ^2.4.0
  local_auth: ^2.1.7
  animate_do: ^3.3.4
  flutter_speed_dial: ^7.0.0
  file_picker: ^6.1.1
  google_mobile_ads: ^3.0.0
  calendar_date_picker2: ^0.5.3
  flutter_localization: ^0.2.0
  intl: ^0.18.0
  syncfusion_flutter_charts: ^20.0.0
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconos/iconologo.png"
  adaptive_icon_background: "assets/iconos/iconologo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
